# zsh configuration file

ZSHC="$HOME/.zsh"
ZSH_CUSTOM="$ZSHC/custom"

COMPLETION_WAITING_DOTS=true
plugins=(archlinux cdenv git mercurial ssh-gpg-monkeysphere-agents svn undistract-me)
setopt completealiases
setopt histignoredups
setopt auto_pushd
unsetopt correct_all

ZSH="$ZSHC/oh-my-zsh"
source "$ZSH/oh-my-zsh.sh"
source "$ZSHC/zsh_theme"

if [ -f /usr/share/doc/pkgfile/command-not-found.zsh ]; then
	source /usr/share/doc/pkgfile/command-not-found.zsh
fi

if [ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
	source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ -f "$ZSHC/zsh_sudo" ]; then
	while read -r COMMAND; do
		alias $COMMAND="sudo $COMMAND"
	done < "$ZSHC/zsh_sudo"
fi

if [ -f "$ZSHC/zsh_aliases" ]; then
	source "$ZSHC/zsh_aliases"
fi

export EDITOR=nano # Don't judge me!
export PATH="/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
export GPGKEY=5CFC3B88974EE250
export PAGER=most
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
